### ISSUE TITLE
Invalid ID field

### ISSUE THREAD

**Issue by hb0nd** [SupaplexOSM/strassenraumkarte-neukoelln#27]
Looks to be a similar issue to #26, where there is no feature matched because the area is small

bbox: [38.80528, -9.23141, 38.80681, -9.22796]

```python
Traceback (most recent call last):
  File "/home/harry/Documents/Git/osm-strassenraumkarte-generator/./generate.py", line 476, in <module>
    import post_processing
  File "/usr/lib64/python3.12/site-packages/qgis/utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/harry/Documents/Git/osm-strassenraumkarte-generator/strassenraumkarte-neukoelln/mapstyle/post_processing.py", line 1150, in <module>
    crossing_line_markings = processing.run('native:hublines', { 'HUBS' : crossing_line_markings_point1, 'HUB_FIELD' : 'id', 'HUB_FIELDS' : ['id'], 'SPOKES' : crossing_line_markings_point2, 'SPOKE_FIELD' : 'id', 'SPOKE_FIELDS' : ['crossing','crossing_ref','temporary'], 'OUTPUT': 'memory:'})['OUTPUT']
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/qgis/python/plugins/processing/tools/general.py", line 109, in run
    return Processing.runAlgorithm(algOrName, parameters, onFinish, feedback, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/qgis/python/plugins/processing/core/Processing.py", line 176, in runAlgorithm
    ret, results = execute(alg, parameters, context, feedback, catch_exceptions=False)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/qgis/python/plugins/processing/gui/AlgorithmExecutor.py", line 70, in execute
    results, ok = alg.run(parameters, context, feedback, {}, False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_core.QgsProcessingException: Invalid ID field

```

**Comment by tordans** [comment]
New project is at https://github.com/osmberlin/strassenraumkarte; this project can be considered an archive. Therefore I am closing here.
